### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by nkshah2** [supertokens/create-supertokens-app#2]
## Related issues
https://github.com/supertokens/for-zenhub/issues/147

## Remaining work
- [x] Add boilerplate for different stacks
- [x] Confirm that running for python and golang works fine (even when setup required multiple steps)
- [x] Confirm that boilerplate apps work fine
- [ ] Npm configs (to make sure only the relevant files and folders are pushed to npm when publishing)
- [x] Confirm everything works on 
    - [x] Mac
    - [x] Linux
    - [x] Windows (with Powershell)
    - [x] Windows with command prompt
